repositoryUrl: https://github.com/herveDarritchon/foundryvtt-swerpg.git

branches:
  - main
  - next
  - '/.*cicd.*/'

plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: chore
          release: patch
        - type: docs
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: perf
          release: patch
        - type: breaking
          release: minor
      parserOpts:
        noteKeywords: [ 'BREAKING CHANGE' ]
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/exec'
    - prepareCmd: |
        node ./update-system-json.cjs && node ./append-links-to-changelog.cjs
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - system.json
      message: |
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - - '@semantic-release/github'
    - successComment: false
      failComment: false
      assets: [ ]
