repositoryUrl: https://github.com/<ton_user>/<ton_repo>.git

branches:
  - main
  - next
  - '/.*cicd.*/'

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - src/system.json
      message: |
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - - '@semantic-release/github'
    - successComment: false
      failComment: false
      assets: []

prepare:
  - path: '@semantic-release/changelog'
    changelogFile: CHANGELOG.md
  - path: './update-system-json.cjs'
  - path: '@semantic-release/git'
    assets:
      - src/system.json
      - CHANGELOG.md
    message: |
      chore(release): ${nextRelease.version} [skip ci]

      ${nextRelease.notes}
