/**
 * Length of the canonical ActiveEffect ID generated by getEffectId.
 * IDs are truncated and padded to this exact length for consistency.
 * @type {number}
 */
export const EFFECT_ID_LENGTH = 16

/**
 * Divisor used to compute half-ability DoT (damage-over-time) values.
 * DoT effects that scale with half an ability use Math.floor(ability / HALF_ABILITY_DIVISOR).
 * @type {number}
 */
export const HALF_ABILITY_DIVISOR = 2

/**
 * Get a standardized 16 character ID that can be used for the ActiveEffect.
 * @param {string} label    The active effect label
 * @returns {string}        The standardized ID
 */
export function getEffectId(label) {
  return label.slugify({ replacement: '', lowercase: false, strict: true }).slice(0, EFFECT_ID_LENGTH).padEnd(EFFECT_ID_LENGTH, '0')
}

/**
 * Build the ActiveEffect data for the Bleeding condition, dealing piercing damage over time.
 * @param {object} actor
 * @param {object} target
 * @param {object} root0
 * @param {string} root0.ability
 * @param {string} root0.damageType
 */
export function bleeding(actor, target, { ability = 'dexterity', damageType = 'piercing' } = {}) {
  return {
    _id: getEffectId('Bleeding'),
    name: 'Bleeding',
    icon: 'icons/skills/wounds/blood-spurt-spray-red.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    flags: {
      swerpg: {
        dot: {
          health: actor.system.abilities[ability].value,
          damageType,
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Burning condition, dealing fire damage over time to health and morale.
 * @param {object} actor
 * @param {object} target
 */
export function burning(actor, target) {
  return {
    _id: getEffectId('Burning'),
    name: 'Burning',
    icon: 'icons/magic/fire/projectile-smoke-swirl-red.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    flags: {
      swerpg: {
        dot: {
          health: actor.system.abilities.intellect.value,
          morale: actor.system.abilities.intellect.value,
          damageType: 'fire',
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Chilled condition, applying cold damage and the slowed status.
 * @param {object} actor
 * @param {object} target
 */
export function chilled(actor, target) {
  return {
    _id: getEffectId('Chilled'),
    name: 'Chilled',
    icon: 'icons/magic/water/orb-ice-web.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    statuses: ['slowed'],
    flags: {
      swerpg: {
        dot: {
          health: Math.floor(actor.system.abilities.wisdom.value / HALF_ABILITY_DIVISOR),
          damageType: 'cold',
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Confusion condition, dealing psychic morale damage and applying the disoriented status.
 * @param {object} actor
 * @param {object} target
 */
export function confusion(actor, target) {
  return {
    _id: getEffectId('Confusion'),
    name: 'Confusion',
    icon: 'icons/magic/air/air-burst-spiral-pink.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    statuses: ['disoriented'],
    flags: {
      swerpg: {
        dot: {
          morale: Math.floor(actor.system.abilities.intellect.value / HALF_ABILITY_DIVISOR),
          damageType: 'psychic',
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Corroding condition, dealing acid damage over three turns.
 * @param {object} actor
 * @param {object} target
 */
export function corroding(actor, target) {
  return {
    _id: getEffectId('Corroding'),
    name: 'Corroding',
    icon: 'icons/magic/earth/orb-stone-smoke-teal.webp',
    duration: { turns: 3 },
    origin: actor.uuid,
    flags: {
      swerpg: {
        dot: {
          health: actor.system.abilities.wisdom.value,
          damageType: 'acid',
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Decay condition, dealing corruption damage over three turns.
 * @param {object} actor
 * @param {object} target
 */
export function decay(actor, target) {
  return {
    _id: getEffectId('Decay'),
    name: 'Decay',
    icon: 'icons/magic/unholy/strike-beam-blood-red-purple.webp',
    duration: { turns: 3 },
    origin: actor.uuid,
    flags: {
      swerpg: {
        dot: {
          health: actor.system.abilities.intellect.value,
          damageType: 'corruption',
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Entropy condition, dealing void damage and applying the frightened status.
 * @param {object} actor
 * @param {object} target
 */
export function entropy(actor, target) {
  return {
    _id: getEffectId('Entropy'),
    name: 'Entropy',
    icon: 'icons/magic/unholy/orb-swirling-teal.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    statuses: ['frightened'],
    flags: {
      swerpg: {
        dot: {
          health: Math.floor(actor.system.abilities.presence.value / HALF_ABILITY_DIVISOR),
          damageType: 'void',
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Irradiated condition, dealing radiant damage to both health and morale.
 * @param {object} actor
 * @param {object} target
 */
export function irradiated(actor, target) {
  return {
    _id: getEffectId('Irradiated'),
    name: 'Irradiated',
    icon: 'icons/magic/light/beams-rays-orange-purple-large.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    flags: {
      swerpg: {
        dot: {
          health: actor.system.abilities.presence.value,
          morale: actor.system.abilities.presence.value,
          damageType: 'radiant',
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Mending condition, restoring health each turn.
 * @param {object} actor
 * @param {object} target
 */
export function mending(actor, target) {
  return {
    _id: getEffectId('Mending'),
    name: 'Mending',
    icon: 'icons/magic/life/cross-beam-green.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    flags: {
      swerpg: {
        dot: {
          health: -actor.system.abilities.wisdom.value,
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Inspired condition, restoring morale each turn.
 * @param {object} actor
 * @param {object} target
 */
export function inspired(actor, target) {
  return {
    _id: getEffectId('Inspired'),
    name: 'Inspired',
    icon: 'icons/magic/light/explosion-star-glow-silhouette.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    flags: {
      swerpg: {
        dot: {
          morale: -actor.system.abilities.presence.value,
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Poisoned condition, dealing poison damage over six turns.
 * @param {object} actor
 * @param {object} target
 */
export function poisoned(actor, target) {
  return {
    _id: getEffectId('Poisoned'),
    name: 'Poisoned',
    icon: 'icons/magic/unholy/orb-smoking-green.webp',
    duration: { turns: 6 },
    origin: actor.uuid,
    flags: {
      swerpg: {
        dot: {
          health: actor.system.abilities.intellect.value,
          damageType: 'poison',
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Shocked condition, dealing electricity morale damage and applying the staggered status.
 * @param {object} actor
 * @param {object} target
 */
export function shocked(actor, target) {
  return {
    _id: getEffectId('Shocked'),
    name: 'Shocked',
    icon: 'icons/magic/lightning/bolt-strike-forked-blue.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    statuses: ['staggered'],
    flags: {
      swerpg: {
        dot: {
          morale: Math.floor(actor.system.abilities.intellect.value / HALF_ABILITY_DIVISOR),
          damageType: 'electricity',
        },
      },
    },
  }
}

/**
 * Build the ActiveEffect data for the Staggered condition, applying the staggered status for one turn.
 * @param {object} actor
 * @param {object} target
 */
export function staggered(actor, target) {
  return {
    _id: getEffectId('Staggered'),
    name: 'Staggered',
    icon: 'icons/skills/melee/strike-hammer-destructive-orange.webp',
    duration: { turns: 1 },
    origin: actor.uuid,
    statuses: ['staggered'],
  }
}
