export const QUALITIES = Object.freeze({
  BLAST: { key: 'blast', hasRank: true },
  BURN: { key: 'burn', hasRank: true },
  PIERCE: { key: 'pierce', hasRank: true },
  VICIOUS: { key: 'vicious', hasRank: true },
  AUTO_FIRE: { key: 'autoFire', hasRank: true },
  DISORIENT: { key: 'disorient', hasRank: true },
  ENSNARE: { key: 'ensnare', hasRank: true },
  KNOCKDOWN: { key: 'knockdown', hasRank: true },
  LIMITED_AMMO: { key: 'limitedAmmo', hasRank: true },
  SUNDER: { key: 'sunder', hasRank: true },
  ACCURATE: { key: 'accurate', hasRank: false },
  BREACH: { key: 'breach', hasRank: false },
  CONCUSSIVE: { key: 'concussive', hasRank: true },
  CORTOSIS: { key: 'cortosis', hasRank: false },
  CUMBERSOME: { key: 'cumbersome', hasRank: false },
  DEFENSIVE: { key: 'defensive', hasRank: false },
  DEFLECTION: { key: 'deflection', hasRank: false },
  GUIDED: { key: 'guided', hasRank: false },
  INACCURATE: { key: 'inaccurate', hasRank: false },
  INFERIOR: { key: 'inferior', hasRank: false },
  ION: { key: 'ion', hasRank: false },
  LINKED: { key: 'linked', hasRank: false },
  PREPARE: { key: 'prepare', hasRank: false },
  SLOW_FIRING: { key: 'slowFiring', hasRank: false },
  STUN: { key: 'stun', hasRank: false },
  STUN_SETTING: { key: 'stunSetting', hasRank: false },
  STUN_DAMAGE: { key: 'stunDamage', hasRank: false },
  SUPERIOR: { key: 'superior', hasRank: false },
  TRACTOR: { key: 'tractor', hasRank: false },
  UNWIELDY: { key: 'unwieldy', hasRank: false },
  TWO_HANDED: { key: 'twoHanded', hasRank: false },
})

export const OGGDUDE_QUALITY_MAP = {
  BLAST: 'blast',
  BURN: 'burn',
  PIERCE: 'pierce',
  VICIOUS: 'vicious',
  AUTO_FIRE: 'autoFire',
  DISORIENT: 'disorient',
  ENSNARE: 'ensnare',
  KNOCKDOWN: 'knockdown',
  LIMITED_AMMO: 'limitedAmmo',
  SUNDER: 'sunder',
  ACCURATE: 'accurate',
  BREACH: 'breach',
  CONCUSSIVE: 'concussive',
  CORTOSIS: 'cortosis',
  CUMBERSOME: 'cumbersome',
  DEFENSIVE: 'defensive',
  DEFLECTION: 'deflection',
  GUIDED: 'guided',
  INACCURATE: 'inaccurate',
  INFERIOR: 'inferior',
  ION: 'ion',
  LINKED: 'linked',
  PREPARE: 'prepare',
  SLOW_FIRING: 'slowFiring',
  STUN: 'stun',
  STUN_SETTING: 'stunSetting',
  STUN_DAMAGE: 'stunDamage',
  SUPERIOR: 'superior',
  TRACTOR: 'tractor',
}

export function getQualityConfig(key) {
  return Object.values(QUALITIES).find((q) => q.key === key)
}
