name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Combine CSS files into a single CSS file
      - name: Combine CSS files
        run: |
          cat styles/*.css > swerpg.css

      # Get part of the tag after the `v`.
      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      # Modify manifest version, download, esmodules, styles, remove hotreload.
      - name: Modify Manifest to remove HotReload
        uses: microsoft/variable-substitution@v1
        with:
          files: "system.json"
        env:
          flags.hotReload: false
          version: ${{steps.get_version.outputs.version-without-v}}
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip
          esmodules: "[\"swerpg.mjs\"]"
          styles: "[\"swerpg.css\"]"

      # Set up Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'

      # `npm ci` is recommended:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
      - name: Install Dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      # Run build scripts
      - name: Build All
        run: |
          npm run db:pack
          npm run build
          mv --force public/swerpg.mjs swerpg.mjs

      # Create zip file.
      - name: Create ZIP archive
        run: zip -r ./system.zip system.json swerpg.css swerpg.mjs packs/ lang/ templates/ assets/

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      # Create a release for this specific version.
      - name: Update Release with Files
        if: "!github.event.release.prerelease"
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./system.json, ./system.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
