name: Create System Files For GitHub Release

env:
  project_url: "https://github.com/${{github.repository}}"
  latest_manifest_url: "https://github.com/${{github.repository}}/releases/latest/download/system.json"
  release_module_url: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Modify system.json With Release-Specific Values
        uses: cschleiden/replace-tokens@v1
        with:
          files: 'system.json'
        env:
          VERSION: ${{ steps.get_version.outputs.version-without-v }}
          URL: ${{ env.project_url }}
          MANIFEST: ${{ env.latest_manifest_url }}
          DOWNLOAD: ${{ env.release_module_url }}

      - name: Install Dependencies
        run: npm ci

      # Si tu as une étape de build spécifique, ajoute-la ici
      # - name: Build System Assets
      #   run: npm run build

      - name: Create System Archive
        run: |
          zip -r system.zip \
            system.json \
            swerpg.mjs \
            README.md \
            CHANGELOG.md \
            LICENSE \
            assets/ \
            styles/ \
            lang/ \
            templates/ \
            packs/

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json, ./system.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}

      # Optionnel : ping l'API FoundryVTT si tu as un token FVTT_PACKAGE_RELEASE_TOKEN
      # - name: Deploy to Foundry Package Listing
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'https://api.foundryvtt.com/_api/packages/release_version'
      #     method: 'POST'
      #     contentType: 'application/json'
      #     customHeaders: '{"Authorization": "${{ secrets.FVTT_PACKAGE_RELEASE_TOKEN }}"}'
      #     data: '{
      #       "id": "swerpg",
      #       "dry-run": false,
      #       "release": {
      #         "version": "${{ github.event.release.tag_name }}",
      #         "manifest": "https://github.com/herveDarritchon/foundryvtt-swerpg/releases/download/${{ github.event.release.tag_name }}/system.json",
      #         "notes": "https://github.com/herveDarritchon/foundryvtt-swerpg/blob/main/CHANGELOG.md",
      #         "compatibility": {
      #           "minimum": "12",
      #           "verified": "13.334"
      #         }
      #       }
      #     }'
