name: Unit Tests & Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 # ou "latest" si tu préfères

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # adapte à ta version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm run test -- --coverage

      - name: Upload coverage to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage

  playwright-e2e:
    runs-on: ubuntu-latest
    needs: test
    env:
      E2E_FOUNDRY_BASE_URL: ${{ secrets.E2E_FOUNDRY_BASE_URL }}
      E2E_FOUNDRY_ADMIN_PASSWORD: ${{ secrets.E2E_FOUNDRY_ADMIN_PASSWORD }}
      E2E_FOUNDRY_USERNAME: ${{ secrets.E2E_FOUNDRY_USERNAME }}
      E2E_FOUNDRY_PASSWORD: ${{ secrets.E2E_FOUNDRY_PASSWORD }}
      E2E_FOUNDRY_WORLD: ${{ secrets.E2E_FOUNDRY_WORLD }}

    steps:
      - uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright E2E tests
        run: pnpm e2e

